2023-05-08 09:44:09,342 [log | ERROR] home - User logged in from generic login page @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-08 09:44:21,285 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-08 09:44:48,837 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-08 10:06:08,078 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-08 10:24:19,416 [log | ERROR] home - User logged in from generic login page @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-08 10:24:30,489 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-08 10:55:00,249 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-08 11:43:28,068 [log | ERROR] home - User logged in from generic login page @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-08 11:43:44,694 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-08 11:49:46,681 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-10 12:38:40,301 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-10 12:42:56,419 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-10 14:42:31,274 [log | ERROR] home - User logged in from generic login page @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-10 14:42:37,643 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-10 14:56:43,839 [log | ERROR] CAF column contains non-numeric data @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-10 14:59:13,793 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-10 14:59:21,513 [log | ERROR] CAF column contains non-numeric data @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-10 14:59:55,993 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-10 15:01:05,654 [log | ERROR] Error was retutned by OTM - An Undefined Error Has Occurred. Please Try Again Later. @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-10 15:05:36,291 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-10 15:06:19,795 [log | ERROR] Error while generating xml payload [Errno 2] No such file or directory: '<Transmission><TransmissionHeader /><TransmissionBody><GLogXMLElement><CSVDataLoad><CsvCommand>iu</CsvCommand><CsvTableName>RATE_OFFERING</CsvTableName><CsvRow>"RATE_OFFERING"</CsvRow><CsvColumnList>RATE_OFFERING_GID,RATE_OFFERING_XID,RATE_OFFERING_TYPE_GID,RATE_OFFERING_DESC,SERVPROV_GID,CURRENCY_GID,TRANSPORT_MODE_GID,RATE_SERVICE_GID,RATE_VERSION_GID,RATE_DISTANCE_GID,EXCHANGE_RATE_GID,PERSPECTIVE,IS_ACTIVE,DOMAIN_NAME</CsvColumnList><CsvRow>"CPK.FXFE-TL-USD-RO-20230510","FXFE-TL-USD-RO-20230510","TL","FXFE-TL-USD-RO-20230510","CPK.100387","USD","TL","CPK.FEDEX-TL-USD-BULK-2023","CPK.2023-2023","LOOKUP ELSE ESTIMATE","DEFAULT","A","Y","CPK"</CsvRow><CsvRow>"CPK.PAZC-TL-USD-RO-20230510","PAZC-TL-USD-RO-20230510","TL","PAZC-TL-USD-RO-20230510","CPK.198358","USD","TL","CPK.DHL E-TL-USD-BULK-2023","CPK.2023-2023","LOOKUP ELSE ESTIMATE","DEFAULT","A","Y","CPK"</CsvRow></CSVDataLoad></GLogXMLElement><GLogXMLElement><CSVDataLoad><CsvCommand>iu</CsvCommand><CsvTableName>X_LANE</CsvTableName><CsvRow>"X_LANE"</CsvRow><CsvColumnList>X_LANE_GID,X_LANE_XID,SOURCE_LOCATION_GID,SOURCE_CITY,SOURCE_PROVINCE_CODE,SOURCE_POSTAL_CODE,SOURCE_COUNTRY_CODE3_GID,SOURCE_GEO_HIERARCHY_GID,DEST_LOCATION_GID,DEST_CITY,DEST_PROVINCE_CODE,DEST_POSTAL_CODE,DEST_COUNTRY_CODE3_GID,DEST_GEO_HIERARCHY_GID,SOURCE_REGION_GID,DEST_REGION_GID,DOMAIN_NAME</CsvColumnList><CsvRow>"CPK.L-SAN DIEGO-US-1000056436","L-SAN DIEGO-US-1000056436","","SAN DIEGO","","","US","CITY/COUNTRY","CPK.1000056436","","","","","LOCATION","","","CPK"</CsvRow><CsvRow>"CPK.L-ACWORTH-US-1000056740","L-ACWORTH-US-1000056740","","ACWORTH","","","US","CITY/COUNTRY","CPK.1000056740","","","","","LOCATION","","","CPK"</CsvRow><CsvRow>"CPK.L-NYE-US-1000062542","L-NYE-US-1000062542","","NYE","","","US","CITY/COUNTRY","CPK.1000062542","","","","","LOCATION","","","CPK"</CsvRow><CsvRow>"CPK.L-LAS VEGAS-US-1000062690","L-LAS VEGAS-US-1000062690","","LAS VEGAS","","","US","CITY/COUNTRY","CPK.1000062690","","","","","LOCATION","","","CPK"</CsvRow><CsvRow>"CPK.L-BROWNS SUMMIT-US-1000062945","L-BROWNS SUMMIT-US-1000062945","","BROWNS SUMMIT","","","US","CITY/COUNTRY","CPK.1000062945","","","","","LOCATION","","","CPK"</CsvRow><CsvRow>"CPK.L-HOBBS-US-1000064274","L-HOBBS-US-1000064274","","HOBBS","","","US","CITY/COUNTRY","CPK.1000064274","","","","","LOCATION","","","CPK"</CsvRow><CsvRow>"CPK.L-MIDLAND-US-1000064948","L-MIDLAND-US-1000064948","","MIDLAND","","","US","CITY/COUNTRY","CPK.1000064948","","","","","LOCATION","","","CPK"</CsvRow><CsvRow>"CPK.L-HAMMOND-US-1000065080","L-HAMMOND-US-1000065080","","HAMMOND","","","US","CITY/COUNTRY","CPK.1000065080","","","","","LOCATION","","","CPK"</CsvRow><CsvRow>"CPK.L-ROSENBERG-US-1000065156","L-ROSENBERG-US-1000065156","","ROSENBERG","","","US","CITY/COUNTRY","CPK.1000065156","","","","","LOCATION","","","CPK"</CsvRow><CsvRow>"CPK.L-TULSA-US-1000065305","L-TULSA-US-1000065305","","TULSA","","","US","CITY/COUNTRY","CPK.1000065305","","","","","LOCATION","","","CPK"</CsvRow></CSVDataLoad></GLogXMLElement><GLogXMLElement><CSVDataLoad><CsvCommand>iu</CsvCommand><CsvTableName>RATE_SERVICE</CsvTableName><CsvRow>"RATE_SERVICE"</CsvRow><CsvColumnList>RATE_SERVICE_GID,RATE_SERVICE_XID,RATE_SERVICE_NAME,RATE_SERVICE_TYPE,DOMAIN_NAME</CsvColumnList><CsvRow>"CPK.FXFE-TL-USD-BULK-2023","FXFE-TL-USD-BULK-2023","FXFE-TL-USD-BULK-2023","LOOKUP","CPK"</CsvRow><CsvRow>"CPK.PAZC-TL-USD-BULK-2023","PAZC-TL-USD-BULK-2023","PAZC-TL-USD-BULK-2023","LOOKUP","CPK"</CsvRow></CSVDataLoad></GLogXMLElement></TransmissionBody></Transmission>' @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-10 15:10:10,650 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-10 15:10:29,057 [log | ERROR] Error was retutned by OTM - An Undefined Error Has Occurred. Please Try Again Later. @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-10 15:22:04,836 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-10 15:22:22,945 [log | ERROR] Error was retutned by OTM - An Undefined Error Has Occurred. Please Try Again Later. @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-10 15:31:01,809 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-10 15:41:07,757 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-10 15:51:30,517 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-12 03:14:25,837 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-12 03:20:05,732 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-12 03:58:56,018 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-12 04:02:55,449 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-12 04:13:44,388 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-12 04:18:11,115 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-12 04:36:52,570 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-12 04:37:00,970 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-12 04:56:16,922 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-12 04:58:49,939 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-12 10:07:18,909 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-12 10:14:14,513 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-12 10:49:55,501 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-12 11:32:58,046 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-12 11:44:29,653 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-12 11:44:48,754 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-12 11:50:19,858 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-12 11:55:32,202 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-12 12:03:17,087 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-12 12:04:33,792 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-12 12:07:15,508 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-12 12:08:29,834 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-12 12:08:53,598 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-12 13:09:04,635 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-12 13:17:42,843 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-17 09:37:49,437 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-17 09:39:10,486 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-17 16:18:49,149 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-17 16:19:16,000 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-17 17:32:12,465 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-17 17:55:19,419 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-17 18:04:37,836 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-17 18:08:02,733 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-17 18:08:53,145 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-18 04:45:51,797 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-18 04:46:03,911 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-18 04:46:05,384 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-18 04:51:28,866 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-18 15:33:20,597 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-23 09:33:35,395 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-23 09:35:51,898 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-23 09:38:50,987 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-23 10:10:40,708 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 05:51:16,700 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 05:53:16,264 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 05:56:55,890 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 06:07:20,258 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 06:18:56,684 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 06:27:23,158 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 07:41:12,151 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 07:57:37,639 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 08:31:01,344 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 09:07:53,877 [log | ERROR] Error while generating xml payload list index out of range @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 09:08:00,334 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 10:28:07,830 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 10:28:23,003 [log | ERROR] get_transmission_status - name 'break_profile' is not defined @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 10:28:49,868 [log | ERROR] get_transmission_status - name 'break_profile' is not defined @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 10:29:10,763 [log | ERROR] get_transmission_status - name 'break_profile' is not defined @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 10:29:14,479 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 10:29:24,792 [log | ERROR] get_transmission_status - name 'break_profile' is not defined @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 10:35:24,722 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 10:35:25,816 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 10:36:00,581 [log | ERROR] get_transmission_status - name 'break_profile' is not defined @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 10:37:43,490 [log | ERROR] get_transmission_status - no element found: line 1, column 3942 @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 10:40:01,470 [log | ERROR] get_transmission_status - no element found: line 1, column 3942 @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 10:41:51,678 [log | ERROR] Error while generating xml payload list index out of range @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 10:42:03,826 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 10:43:09,749 [log | ERROR] get_transmission_status - junk after document element: line 1, column 1955 @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 10:47:02,180 [log | ERROR] get_transmission_status - no element found: line 1, column 3942 @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 10:57:21,076 [log | ERROR] get_transmission_status - local variable 'status_code' referenced before assignment @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 10:58:15,374 [log | ERROR] get_transmission_status - no element found: line 1, column 3942 @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 11:16:57,266 [log | ERROR] get_transmission_status - response code 500 - <Response [500]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 11:16:57,273 [log | ERROR]  @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 11:18:03,744 [log | ERROR] get_transmission_status - no element found: line 1, column 0 @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 11:19:16,475 [log | ERROR] get_transmission_status - response code 500 - <Response [500]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 11:19:16,483 [log | ERROR]  @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 11:19:49,839 [log | ERROR] get_transmission_status - response code 500 - <Response [500]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 11:19:49,845 [log | ERROR]  @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 11:27:36,661 [log | ERROR] RATE_GEO_ACCESSORIAL ORA-02291: integrity constraint (GLOGOWNER.FK_RGA_RGGID) violated - parent key not foundORA-06512: at line 1ORA-06512: at line 1
 RATE_GEO_ACCESSORIAL ORA-02291: integrity constraint (GLOGOWNER.FK_RGA_ACCESSORIAL_COST_GID) violated - parent key not foundORA-06512: at line 1ORA-06512: at line 1
 Error string is more than 4000 characters, check the error in OTM.
 RATE_GEO_COST_GROUP ORA-02291: integrity constraint (GLOGOWNER.FK_RGC_RATE_GEO_GID) violated - parent key not found
 RATE_GEO_COST_GROUP ORA-02291: integrity constraint (GLOGOWNER.FK_RGC_RATE_GEO_GID) violated - parent key not found
 RATE_GEO_COST_GROUP ORA-02291: integrity constraint (GLOGOWNER.FK_RGC_RATE_GEO_GID) violated - parent key not found
 RATE_GEO_COST_GROUP ORA-02291: integrity constraint (GLOGOWNER.FK_RGC_RATE_GEO_GID) violated - parent key not found
 RATE_GEO_COST_GROUP ORA-02291: integrity constraint (GLOGOWNER.FK_RGC_RATE_GEO_GID) violated - parent key not found
 RATE_GEO_COST_GROUP ORA-02291: integrity constraint (GLOGOWNER.FK_RGC_RATE_GEO_GID) violated - parent key not found
 RATE_GEO_COST_GROUP ORA-02291: integrity constraint (GLOGOWNER.FK_RGC_RATE_GEO_GID) violated - parent key not found
 RATE_GEO_COST_GROUP ORA-02291: integrity constraint (GLOGOWNER.FK_RGC_RATE_GEO_GID) violated - parent key not found
 RATE_GEO_COST_GROUP ORA-02291: integrity constraint (GLOGOWNER.FK_RGC_RATE_GEO_GID) violated - parent key not found
 RATE_GEO_COST_GROUP ORA-02291: integrity constraint (GLOGOWNER.FK_RGC_RATE_GEO_GID) violated - parent key not found
 Error string is more than 4000 characters, check the error in OTM.
 ACCESSORIAL_COST ORA-12899: value too large for column ??? (actual: 53, maximum: 50)ORA-06512: at line 1ORA-06512: at line 1
 @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 11:29:13,221 [log | ERROR] RATE_GEO_ACCESSORIAL ORA-02291: integrity constraint (GLOGOWNER.FK_RGA_RGGID) violated - parent key not foundORA-06512: at line 1ORA-06512: at line 1
<br>RATE_GEO_ACCESSORIAL ORA-02291: integrity constraint (GLOGOWNER.FK_RGA_ACCESSORIAL_COST_GID) violated - parent key not foundORA-06512: at line 1ORA-06512: at line 1
<br>Error string is more than 4000 characters, check the error in OTM.
<br>RATE_GEO_COST_GROUP ORA-02291: integrity constraint (GLOGOWNER.FK_RGC_RATE_GEO_GID) violated - parent key not found
<br>RATE_GEO_COST_GROUP ORA-02291: integrity constraint (GLOGOWNER.FK_RGC_RATE_GEO_GID) violated - parent key not found
<br>RATE_GEO_COST_GROUP ORA-02291: integrity constraint (GLOGOWNER.FK_RGC_RATE_GEO_GID) violated - parent key not found
<br>RATE_GEO_COST_GROUP ORA-02291: integrity constraint (GLOGOWNER.FK_RGC_RATE_GEO_GID) violated - parent key not found
<br>RATE_GEO_COST_GROUP ORA-02291: integrity constraint (GLOGOWNER.FK_RGC_RATE_GEO_GID) violated - parent key not found
<br>RATE_GEO_COST_GROUP ORA-02291: integrity constraint (GLOGOWNER.FK_RGC_RATE_GEO_GID) violated - parent key not found
<br>RATE_GEO_COST_GROUP ORA-02291: integrity constraint (GLOGOWNER.FK_RGC_RATE_GEO_GID) violated - parent key not found
<br>RATE_GEO_COST_GROUP ORA-02291: integrity constraint (GLOGOWNER.FK_RGC_RATE_GEO_GID) violated - parent key not found
<br>RATE_GEO_COST_GROUP ORA-02291: integrity constraint (GLOGOWNER.FK_RGC_RATE_GEO_GID) violated - parent key not found
<br>RATE_GEO_COST_GROUP ORA-02291: integrity constraint (GLOGOWNER.FK_RGC_RATE_GEO_GID) violated - parent key not found
<br>Error string is more than 4000 characters, check the error in OTM.
<br>ACCESSORIAL_COST ORA-12899: value too large for column ??? (actual: 53, maximum: 50)ORA-06512: at line 1ORA-06512: at line 1
 @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 11:41:10,882 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 11:42:23,033 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 11:49:28,049 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 11:50:11,555 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 11:51:46,590 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 11:58:40,861 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 12:08:19,094 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 12:11:55,540 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 12:18:25,975 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 13:00:06,664 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 13:04:32,946 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 13:07:40,586 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 13:11:36,547 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 14:02:19,945 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 14:22:57,343 [log | ERROR] Error while generating xml payload list index out of range @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 14:24:39,780 [log | ERROR] Error while generating xml payload list index out of range @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 14:24:43,461 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 14:25:01,576 [log | ERROR] Error while generating xml payload list index out of range @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 14:26:09,497 [log | ERROR] Error while generating xml payload list index out of range @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 14:26:13,311 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 14:29:13,592 [log | ERROR] Error while generating xml payload list index out of range @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 14:29:32,314 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 14:29:48,024 [log | ERROR] Error while generating xml payload list index out of range @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 14:33:42,221 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 14:33:59,233 [log | ERROR] Error while generating xml payload list index out of range @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 14:34:55,949 [log | ERROR] Error while generating xml payload list index out of range @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 14:35:01,077 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 14:35:16,941 [log | ERROR] Error while generating xml payload list index out of range @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 14:37:54,885 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 14:38:39,823 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 14:39:27,087 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 14:39:58,358 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 14:42:39,409 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-24 14:48:14,356 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-25 03:06:06,698 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-25 03:11:11,389 [log | ERROR] home - User logged in from generic login page @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 03:48:10,282 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 04:02:55,410 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 04:05:26,381 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 04:11:05,367 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 04:13:13,785 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 04:14:41,877 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 04:15:24,627 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 04:16:02,226 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 04:16:42,974 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 04:17:27,089 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 04:25:00,378 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 04:26:54,575 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 04:27:15,579 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 04:27:26,968 [log | ERROR] Uploaded Excel contains no valid rows @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 04:30:48,493 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 04:30:56,310 [log | ERROR] Error while executing expression invalid syntax (<string>, line 1) @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 04:38:19,785 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 04:38:39,719 [log | ERROR] Error while executing expression invalid syntax (<string>, line 1) @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 04:42:22,518 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 04:42:32,280 [log | ERROR] Error while executing expression invalid syntax (<string>, line 1) @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 04:48:36,299 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 04:48:45,882 [log | ERROR] Error while executing expression invalid syntax (<string>, line 1) @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 04:53:28,409 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 04:53:38,745 [log | ERROR] Error while executing expression invalid syntax (<string>, line 1) @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 05:00:58,037 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 05:01:04,960 [log | ERROR] Error while executing expression invalid syntax (<string>, line 1) @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 05:04:55,130 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 05:05:07,249 [log | ERROR] Error while executing expression invalid syntax (<string>, line 1) @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 05:06:46,627 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 05:06:56,734 [log | ERROR] Error while executing expression 'Weight UOM' @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 05:06:56,739 [log | ERROR] Error while executing expression invalid syntax (<string>, line 1) @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 05:21:43,958 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 05:22:10,251 [log | ERROR] Error while executing expression invalid syntax (<string>, line 1) @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 05:22:48,268 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 05:22:56,540 [log | ERROR] Error while executing expression invalid syntax (<string>, line 1) @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 05:42:46,595 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 05:43:00,019 [log | ERROR] Error while executing expression name 'RATE_TYPE' is not defined @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 05:43:00,025 [log | ERROR] Error while executing expression invalid syntax (<string>, line 1) @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 05:45:29,137 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 05:45:38,661 [log | ERROR] Error while executing expression invalid syntax (<string>, line 1) @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 06:06:41,397 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 06:07:00,657 [log | ERROR] Error while executing expression invalid syntax (<string>, line 1) @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 06:12:43,301 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 06:12:51,133 [log | ERROR] Error while executing expression invalid syntax (<string>, line 1) @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 06:21:13,958 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 06:21:21,709 [log | ERROR] Error while executing expression invalid syntax (<string>, line 1) @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 06:42:06,830 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 06:42:12,677 [log | ERROR] Error while executing expression concat_addr - 'Series' object has no attribute 'columns' @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 06:42:13,653 [log | ERROR] Error while executing expression invalid syntax (<string>, line 1) @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 07:05:36,682 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 07:05:45,659 [log | ERROR] Error while executing expression concat_addr_row - 'str' object has no attribute 'str' @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 07:05:46,711 [log | ERROR] Error while executing expression invalid syntax (<string>, line 1) @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 07:07:30,271 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 07:07:39,484 [log | ERROR] Error while executing expression invalid syntax (<string>, line 1) @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 07:11:05,353 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 07:11:16,765 [log | ERROR] Error while executing expression invalid syntax (<string>, line 1) @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 07:16:08,496 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 07:16:15,748 [log | ERROR] Error while executing expression invalid syntax (<string>, line 1) @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 07:26:41,867 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 07:26:49,064 [log | ERROR] Error while executing expression invalid syntax (<string>, line 1) @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 07:35:27,291 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 07:35:33,414 [log | ERROR] Error while executing expression invalid syntax (<string>, line 1) @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 07:50:17,009 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 08:27:12,035 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 08:42:43,481 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 09:05:25,026 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 09:07:22,386 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 09:12:21,299 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 09:13:43,832 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 09:22:37,805 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 09:34:48,363 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 09:39:41,422 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 09:40:00,934 [log | ERROR] is_transmission_successfully_completed - not well-formed (invalid token): line 1, column 388 @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 09:40:09,363 [log | ERROR] is_transmission_successfully_completed - not well-formed (invalid token): line 1, column 388 @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 09:40:26,506 [log | ERROR] is_transmission_successfully_completed - not well-formed (invalid token): line 1, column 388 @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 09:45:50,313 [log | ERROR] is_transmission_successfully_completed - not well-formed (invalid token): line 1, column 388 @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 09:45:59,619 [log | ERROR] is_transmission_successfully_completed - not well-formed (invalid token): line 1, column 388 @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 09:50:25,237 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 09:51:09,158 [log | ERROR] is_transmission_successfully_completed - not well-formed (invalid token): line 1, column 388 @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 09:54:47,439 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 09:58:31,643 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 10:03:41,268 [log | ERROR] Error while executing expression for RATE_GEO_COST_GROUP_GID-'Equipment' @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 10:03:41,270 [log | ERROR] Error while executing expression for RATE_GEO_COST_GROUP_XID-'Equipment' @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 10:03:42,606 [log | ERROR] Error while executing expression for RATE_GEO_COST_GROUP_GID-'Equipment' @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 10:12:42,816 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 10:20:48,310 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 11:00:23,765 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 11:46:51,463 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 11:50:41,085 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 11:53:16,609 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 12:06:55,333 [log | ERROR] get_transmission_status - no element found: line 1, column 0 @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 12:11:03,719 [log | ERROR] get_transmission_status - no element found: line 1, column 0 @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 12:13:08,697 [log | ERROR] get_transmission_status - no element found: line 1, column 0 @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 12:19:12,755 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-27 12:25:24,400 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-28 04:10:46,731 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-28 04:17:04,047 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-28 04:17:21,708 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-28 04:40:21,773 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-28 04:44:46,243 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-29 11:05:55,004 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-29 11:09:27,034 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-29 11:11:47,930 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-29 11:11:59,600 [log | ERROR] get_contracts - response code 500 - <Response [500]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-29 11:15:15,530 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-29 11:19:40,012 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-29 11:20:58,355 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-29 11:24:42,638 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-29 11:26:25,856 [log | ERROR] Error while executing expression for SERVICE_TIME_VALUE-'Service Time Value' @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-29 11:26:25,899 [log | ERROR] Error while executing expression for EFFECTIVE_DATE-'Start Date' @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-29 11:26:25,899 [log | ERROR] Error while executing expression for EXPIRATION_DATE-'End Date' @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-29 11:32:26,402 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-29 11:32:35,431 [log | ERROR] Error while executing expression for SERVICE_TIME_VALUE-'Service Time Value' @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-29 11:32:35,491 [log | ERROR] Error while executing expression for EFFECTIVE_DATE-'Start Date' @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-29 11:32:35,491 [log | ERROR] Error while executing expression for EXPIRATION_DATE-'End Date' @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-29 11:35:59,797 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-29 11:36:09,146 [log | ERROR] Error while executing expression for SERVICE_TIME_VALUE-'Service Time Value' @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-29 11:36:09,191 [log | ERROR] Error while executing expression for EFFECTIVE_DATE-'Start Date' @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-29 11:36:09,192 [log | ERROR] Error while executing expression for EXPIRATION_DATE-'End Date' @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-29 11:38:33,044 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-29 11:38:41,973 [log | ERROR] Error while executing expression for SERVICE_TIME_VALUE-'Service Time Value' @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-29 11:38:42,029 [log | ERROR] Error while executing expression for EFFECTIVE_DATE-'Start Date' @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-29 11:38:42,030 [log | ERROR] Error while executing expression for EXPIRATION_DATE-'End Date' @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-29 11:43:39,608 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-29 11:43:50,847 [log | ERROR] Error while executing expression for SERVICE_TIME_VALUE-'Service Time Value' @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-29 11:43:50,907 [log | ERROR] Error while executing expression for EFFECTIVE_DATE-'Start Date' @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-29 11:43:50,908 [log | ERROR] Error while executing expression for EXPIRATION_DATE-'End Date' @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-29 11:53:20,409 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-29 11:53:37,438 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-29 11:56:45,367 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-29 11:57:32,740 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 07:40:00,552 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 07:40:11,896 [log | ERROR] Error while executing expression for SERVICE_TIME_VALUE-'Service Time Value' @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 07:40:11,960 [log | ERROR] Error while executing expression for EFFECTIVE_DATE-'Start Date' @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 07:40:11,961 [log | ERROR] Error while executing expression for EXPIRATION_DATE-'End Date' @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 07:48:35,628 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 07:48:47,887 [log | ERROR] Error while executing expression for SERVICE_TIME_VALUE-'Service Time Value' @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 07:48:47,928 [log | ERROR] Error while executing expression for EFFECTIVE_DATE-'Start Date' @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 07:48:47,929 [log | ERROR] Error while executing expression for EXPIRATION_DATE-'End Date' @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 08:26:17,997 [log | ERROR] home - User logged in from generic login page @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 08:26:24,607 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 08:33:28,015 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 08:33:58,995 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 08:34:23,623 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 08:35:54,822 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 08:36:32,618 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 08:36:48,300 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 08:46:22,571 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 08:46:33,894 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 08:47:15,874 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 08:51:00,543 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 08:51:54,068 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 08:52:54,749 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 08:53:19,045 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 08:53:41,102 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 08:54:40,557 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 08:55:05,005 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 09:02:18,820 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 09:03:33,672 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 09:03:52,498 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 09:05:17,876 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 09:06:22,520 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 09:08:43,464 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 09:12:11,613 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 09:13:46,100 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 09:15:20,832 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 09:18:20,209 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 09:20:58,792 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 09:21:03,717 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 09:22:39,197 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 09:23:28,259 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 09:24:03,535 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 09:24:42,687 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 09:25:22,526 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 09:28:05,789 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 09:30:21,825 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 09:30:47,923 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 09:33:15,403 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 09:33:28,797 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 09:51:48,506 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 09:52:18,824 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 09:52:26,799 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 10:12:41,328 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 10:15:54,995 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 10:16:03,068 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 10:16:11,672 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 10:16:39,644 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 10:18:09,547 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 10:19:30,363 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 10:26:57,052 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 10:28:55,444 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 10:32:01,643 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 10:37:14,969 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 10:38:23,143 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 10:39:12,672 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 10:40:07,490 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 10:41:02,273 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 10:41:35,653 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 10:42:02,160 [log | ERROR] Error while executing expression for SERVICE_TIME_VALUE-'Service Time Value' @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 10:42:02,214 [log | ERROR] Error while executing expression for EFFECTIVE_DATE-'Start Date' @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 10:42:02,215 [log | ERROR] Error while executing expression for EXPIRATION_DATE-'End Date' @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 10:43:15,390 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 10:54:43,832 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 10:55:47,513 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 10:56:02,071 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 10:56:14,699 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 10:56:27,023 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 10:56:36,926 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-05-30 10:57:55,422 [log | ERROR] get_instance_status - response code 404 - <Response [404]> @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
2023-06-02 03:35:59,693 [log | ERROR] home - User logged in from generic login page @ D:\TnA\OTM Rate\otm_rate_upload\rate\log.py : 8 : error
